### ISSUE TITLE
Missing MPC header files on OS-X

### ISSUE THREAD

**Issue by floresboy** [rosco-m68k/homebrew-toolchain#1] opened 2020-04-28 18:12 UTC
It seems I'm missing MPC header files on OS-X. any idea how to add them ? Running GCC's ./contrib/download_prerequisites doen't seem to fix it.

Thanks! K

Last 15 lines from /Volumes/Samsung_T5/kamiel/Library/Logs/Homebrew/gcc-cross-m68k@7/01.configure:
checking whether compiler driver understands Ada... no
checking how to compare bootstrapped objects... cmp --ignore-initial=16 $$f1 $$f2
checking for objdir... .libs
checking for the correct version of gmp.h... yes
checking for the correct version of mpfr.h... yes
checking for the correct version of mpc.h... no
configure: error: Building GCC requires GMP 4.2+, MPFR 2.4.0+ and MPC 0.8.0+.
Try the --with-gmp, --with-mpfr and/or --with-mpc options to specify
their locations.  Source code for these libraries can be found at
their respective hosting sites as well as at
ftp://gcc.gnu.org/pub/gcc/infrastructure/.

**Comment by roscopeco** [comment] 2020-04-28 19:31
Fixed by c9975634ec59f470ccd4c2fda193f606e4e254ce but tagged incorrect issue in commit message :/ 

I think this was caused by some missing dependencies that I didn't think would be needed for an m68k cross compiler (I still don't think they are, but if the build requires them it doesn't hurt to have them).

Please retest and close if fixed :)

**Comment by roscopeco** [comment] 2020-07-28 21:45
Closing as no further reports.

**Closed as completed by roscopeco** 2020-07-28 21:45 UTC
